meta_product_name: "FestiPal"
meta_title: "FestiPal - Your #1 Festival Friend."
meta_description: "FestiPal takes the stress out of your festival experience."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
